#!/bin/bash
MusicDir=$HOME/PiMusic
Playlist=$HOME/PiMusic/playlist

# Get list of current songs and randomise
find $Music -type f | egrep -v 'm3u|txt|jpg|url|html*' | sort -R > $Playlist

if ps -ef | grep -v pulseaudio | grep -v grep >/dev/null 2>&1
then
	pulseaudio >/dev/null 2>&1 &
fi

#mplayer -nogui -shuffle -loop 0 -af volnorm=2:0.75 -playlist $Playlist </dev/null
if ! ps -ef | grep mplayer | grep -v grep >/dev/null 2>&1
then
	# Start mplayer, but don't shuffle or loop as we will deal with that
	mplayer nogui -af volnorm=2:0.75 -playlist $Playlist </dev/null
fi
