#!/bin/bash

# Commands
# pt_step 1 (>)		forward in playlist
# quit (q)		exit player
# pause (p)		pause playback
# get_file_name		Gets current playing file
# http://cpansearch.perl.org/src/GBROWN/Gtk2-Ex-MPlayerEmbed-0.02/mplayer-slave-spec.txt

if [ -e stopme ]
then
	rm stopme
fi

if [[ "$1" == "DEBUG" ]]
then
        MUSICDIR="../ignore/music"
	PLAYLIST="../ignore/playlist"
	MIXED="../ignore/mixedlist"
	VOL="1:0.25 -softvol -volume 4"
else
	MUSICDIR="$HOME/PiMusic"
	PLAYLIST="$HOME/PiMusic/playlist"
	MIXED="$HOME/PiMusic/mixedlist"
	VOL="2:0.75"
fi

# Valid audio files mixed cases
# mp3 m4a ogg wav wma
find $MUSICDIR -type f | egrep -i '(mp3|m4a|ogg|wav|wma)$' > $PLAYLIST

if ps -ef | grep -v pulseaudio | grep -v grep >/dev/null 2>&1
then
        pulseaudio >/dev/null 2>&1 &
fi

realquit=0
echo "Randomising play list"
sort --random-sort $PLAYLIST > $MIXED
#perl -MList::Util -e 'print List::Util::shuffle <>' $PLAYLIST > $MIXED

(rm /tmp/piplayer.in; rm /tmp/piplayer.out; rm nohup.out; rm /tmp/pistop) 2>/dev/null

mkfifo /tmp/piplayer.in

if uname -a | grep -vi raspberrypi >/dev/null 2>&1
then
	nohup mplayer -slave -input file=/tmp/piplayer.in -noconsolecontrols -nogui -af volnorm=$VOL -playlist $MIXED >/tmp/piplayer.out 2>/dev/null &
else
	nohup mplayer -slave -input file=/tmp/piplayer.in -noconsolecontrols nogui -af volnorm=$VOL -playlist $MIXED >/tmp/piplayer.out 2>/dev/null &
fi
MPID=$(ps -ef | grep 'mplayer -slave' | grep -v grep | awk '{print $2}')

pkill mplayer-checker
nohup ./mplayer-checker $1 >mpcheck.log 2>&1 &

./PiMplayer
kill $MPID
# pkill mplayer-check

# If stopped restart the whole thing
if [[ ! -e /tmp/pistop ]]
then
  exec ./mplayer-slave $1
fi

(rm /tmp/piplayer.in; rm /tmp/piplayer.out; rm nohup.out; rm /tmp/pistop) 2>/dev/null
