#!/bin/bash

# Script to check that mplayer is still running
# If not restarts whole piece

lasttrack=""
currenttrack=""
#./mplayer-slave $1 &
sleep 60

while :
do
	PID=$(ps -ef | grep 'mplayer -slave' | grep -v grep | awk '{print $2}')
	until [[ -z $PID ]]
	do
		sleep 60
		# Check mplayer is still alive
		PID=$(ps -ef | grep 'mplayer -slave' | grep -v grep | awk '{print $2}')
	done
	# Kill PiMplayer
	kill -9 $(ps -ef | grep PiMplayer | awk '{print $2}')
	#pkill PiMplayer
	#pkill mplayer-slave
	#if [ ! -e /tmp/stopme ]
	#then
	#	# Restart mplayer if not stopped normally
	#	./mplayer-slave $1 &
	#else
	#	rm /tmp/stopme
	#	exit 0
	#fi
done
rm /tmp/stopme
