#!/bin/bash

# Script to check that mplayer is still running
# If not restarts whole piece

lasttrack=""
currenttrack=""
./mplayer-slave &
sleep 60

while :
do
	PID=$(ps -ef | grep 'mplayer -slave' | grep -v grep | awk '{print $2}')
	until [[ -z $PID ]]
	do
		sleep 60
		# Check mplayer is still alive
		PID=$(ps -ef | grep 'mplayer -slave' | grep -v grep | awk '{print $2}')
	done
	pkill PiMplayer
	pkill mplayer-slave
	if [ ! -e stopme ]
	then
		nohup ./mplayer-slave $1 &
	else
		rm stopme
		exit 0
	fi
done
rm stopme
