#!/bin/bash

if [[ -e ../ignore/music ]]
then
        MUSICDIR="../ignore/music"
        PLAYLIST="../ignore/playlist"
        MIXED="../ignore/mixedlist"
        VOL="1:0.25"
else
        MUSICDIR="$HOME/PiMusic"
        PLAYLIST="$HOME/PiMusic/playlist"
        MIXED="$HOME/PiMusic/mixedlist"
        VOL="2:0.75"
fi


curtrack=$(grep -n "/$(./getinfo)$" $MIXED | awk -F: '{print $1}')
echo "Current: $curtrack/$(wc -l <$MIXED)"
